# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: "${APP_NAME}"
fullnameOverride: "${APP_NAME}"
cluster: "${env}"
role: webapp

replicaCount: 1

terminationGracePeriodSeconds : 60
priorityClassName: fifth-class

affinity:
  preferredDuringScheduling:
    topologyKey: kubernetes.io/hostname


image:
  repository: eu.gcr.io/algoan-dev/${APP_NAME}
  tag: ${env}
  pullPolicy: Always

containerPort: 80

datadog:
  enabled: true

# readinessProbe:
#   httpGet:
#     path: /healthz
#     port: 80
#   initialDelaySeconds: 3
#   periodSeconds: 10
#   timeoutSeconds: 5
#   successThreshold: 1
#   failureThreshold: 10

environmentVariables:
  ALGOAN_ENV: "staging"
  NODE_ENV: production

service:
  type: NodePort
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: gce
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local



resources: {}

nodeSelector: {}

tolerations: []