
name: Push File

on:
  push:
    paths:
      - '.helm/values/**'
      - '.spinnaker/**'
      - '.k8s/**'
    branches:
      - develop

jobs:
  copy-helm-values:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: '.helm/values/**'
        destination_repo: 'KhadijaBenAmmar/yelloan-configurations'
        destination_folder: 'reporting'
        destination_branch: helm-values
        user_email: 'khadija.benammar@algoan.com'
        user_name: 'KhadijaBenAmmar'
        commit_message: 'A custom message for the commit'

  copy-spinnaker-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: '.spinnaker/**'
        destination_repo: 'KhadijaBenAmmar/yelloan-configurations'
        destination_folder: 'reporting'
        destination_branch: spinnaker-pipelines
        user_email: 'khadija.benammar@algoan.com'
        user_name: 'KhadijaBenAmmar'
        commit_message: 'A custom message for the commit'

  copy-config-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: '.k8s/configmap/**'
        destination_repo: 'KhadijaBenAmmar/yelloan-configurations'
        destination_folder: 'reporting'
        destination_branch: algoan-dev-v2
        user_email: 'khadija.benammar@algoan.com'
        user_name: 'KhadijaBenAmmar'
        commit_message: 'A custom message for the commit'

  copy-secret-files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: '.k8s/secrets/**'
        destination_repo: 'KhadijaBenAmmar/yelloan-configurations'
        destination_folder: '.secrets/reporting'
        destination_branch: algoan-dev-v2
        user_email: 'khadija.benammar@algoan.com'
        user_name: 'KhadijaBenAmmar'
        commit_message: 'A custom message for the commit'